global.Buffer = global.Buffer || require("buffer").Buffer;

import { useState } from "react";
import { View, StyleSheet } from "react-native";
import { router } from "expo-router";
import { CameraView, useCameraPermissions } from "expo-camera";

import { Authenticator } from "@otplib/core";
import { keyDecoder, keyEncoder } from "@otplib/plugin-thirty-two";
import { createDigest, createRandomBytes } from "@otplib/plugin-crypto-js";
import otpauthUriParser from "otpauth-uri-parser";

import { Button } from "~/components/ui/button";
import { Text } from "~/components/ui/text";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "~/components/ui/alert-dialog";

export default function Camera() {
  const [permission, requestPermission] = useCameraPermissions();
  const [scanned, setScanned] = useState(false);
  const [openAlertWarning, setOpenAlertWarning] = useState(false);
  const [openAlertSuccess, setOpenAlertSuccess] = useState(false);
  const [token, setToken] = useState("");

  if (!permission) {
    // Camera permissions are still loading.
    return <View />;
  }

  if (!permission.granted) {
    // Camera permissions are not granted yet.
    return (
      <View className="flex-1 justify-center items-center ">
        <Text>We need your permission to show the camera</Text>
        <Button onPress={requestPermission} className="w-2/3">
          <Text>Grant Access</Text>
        </Button>
      </View>
    );
  }

  const handleBarcodeScanned = ({ data }: { data: string }) => {
    setScanned(true);

    const parsedData = otpauthUriParser(data);
    if (!parsedData) {
      setOpenAlertWarning(true);
      return false;
    }

    // get secret
    const secret = parsedData?.query?.secret;
    if (!secret) {
      setOpenAlertWarning(true);
      return false;
    }

    // define authenticator
    const authenticator = new Authenticator({
      createDigest,
      createRandomBytes,
      keyDecoder,
      keyEncoder,
    });

    // generate token
    const token = authenticator.generate(secret);

    setToken(token);
    setOpenAlertSuccess(true);
  };

  return (
    <>
      <CameraView
        style={styles.camera}
        onBarcodeScanned={scanned ? undefined : handleBarcodeScanned}
        barcodeScannerSettings={{
          barcodeTypes: ["qr"],
        }}
      ></CameraView>
      <AlertDialog open={openAlertWarning} onOpenChange={setOpenAlertWarning}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Can't scan this QR Code</AlertDialogTitle>
            <AlertDialogDescription>
              Please scan QR Code generated by 2FA PPI APP
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onPress={() => router.navigate("/")}>
              <Text>Cancel</Text>
            </AlertDialogCancel>
            <AlertDialogAction onPress={() => setScanned(false)}>
              <Text>Scan Again</Text>
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
      <AlertDialog open={openAlertSuccess} onOpenChange={setOpenAlertSuccess}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Token generated successfully</AlertDialogTitle>
            <AlertDialogDescription>
              <Text className="text-4xl text-center text-green-500">
                {token}
              </Text>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onPress={() => router.navigate("/")}>
              <Text>Cancel</Text>
            </AlertDialogCancel>
            <AlertDialogAction onPress={() => setScanned(false)}>
              <Text>Scan Again</Text>
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}

const styles = StyleSheet.create({
  camera: {
    flex: 1,
    width: "100%",
  },
});
